const STAT_LABELS: Record<string, string> = {
	age: 'Age',
	gamesPlayed: 'G',
	gamesStarted: 'GS',
	groundOuts: 'GO',
	airOuts: 'AO',
	runs: 'R',
	doubles: '2B',
	triples: '3B',
	homeRuns: 'HR',
	strikeOuts: 'SO',
	baseOnBalls: 'BB',
	intentionalWalks: 'IBB',
	hits: 'H',
	hitByPitch: 'HBP',
	avg: 'AVG',
	atBats: 'AB',
	obp: 'OBP',
	slg: 'SLG',
	ops: 'OPS',
	caughtStealing: 'CS',
	stolenBases: 'SB',
	stolenBasePercentage: 'SB%',
	caughtStealingPercentage: 'CS%',
	groundIntoDoublePlay: 'GIDP',
	numberOfPitches: 'NP',
	plateAppearances: 'PA',
	totalBases: 'TB',
	rbi: 'RBI',
	leftOnBase: 'LOB',
	sacBunts: 'SH',
	sacFlies: 'SF',
	babip: 'BABIP',
	groundOutsToAirouts: 'GO/AO',
	catchersInterference: 'CI',
	atBatsPerHomeRun: 'AB/HR',
	era: 'ERA',
	inningsPitched: 'IP',
	wins: 'W',
	losses: 'L',
	saves: 'SV',
	saveOpportunities: 'SVO',
	holds: 'HLD',
	blownSaves: 'BS',
	earnedRuns: 'ER',
	whip: 'WHIP',
	battersFaced: 'BF',
	outs: 'OUTS',
	gamesPitched: 'GP',
	completeGames: 'CG',
	shutouts: 'SHO',
	strikes: 'STR',
	strikePercentage: 'STR%',
	hitBatsmen: 'HB',
	balks: 'BK',
	wildPitches: 'WP',
	pickoffs: 'PK',
	winPercentage: 'W%',
	pitchesPerInning: 'P/IP',
	gamesFinished: 'GF',
	strikeoutWalkRatio: 'K/BB',
	strikeoutsPer9Inn: 'K/9',
	walksPer9Inn: 'BB/9',
	hitsPer9Inn: 'H/9',
	runsScoredPer9: 'R/9',
	homeRunsPer9: 'HR/9',
	inheritedRunners: 'IR',
	inheritedRunnersScored: 'IRS',
};

export function statLabel(key: string): string {
	return (
		STAT_LABELS[key] ??
		key
			.replaceAll(/([a-z])([A-Z])/gu, '$1 $2')
			.replace(/^./u, (character) => character.toUpperCase())
	);
}
